#!/usr/bin/env python3
"""
make_kick_header.py — generate esp32/kick_rom.h from YOUR Kickstart ROM.

You must own a legal copy of the Kickstart 1.3 ROM (kick34005.A500).
Legal sources: dump it from your own Amiga, or purchase Amiga Forever
(https://www.amigaforever.com) which licenses the ROMs.

Usage:
    python3 make_kick_header.py kick34005.A500 [output_dir]

The generated kick_rom.h is git-ignored on purpose: NEVER commit it.
"""
import sys, os, zlib

EXPECTED_SIZE = 262144           # 256 KB (Kickstart 1.2/1.3)
KNOWN_CRC = {0xC4F0F55F: "Kickstart 1.3 (34.005) A500 — the tested one"}

def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    path = sys.argv[1]
    outdir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "esp32")

    rom = open(path, "rb").read()
    if len(rom) != EXPECTED_SIZE:
        print(f"WARNING: size is {len(rom)} bytes, expected {EXPECTED_SIZE} (256KB).")
        print("A 512KB ROM is Kickstart 2.0+; this emulator targets 1.3.")
    crc = zlib.crc32(rom) & 0xFFFFFFFF
    print(f"ROM CRC32: {crc:08X} — {KNOWN_CRC.get(crc, 'not the tested 1.3 ROM (may still work)')}")

    out = os.path.join(outdir, "kick_rom.h")
    with open(out, "w") as f:
        f.write("// kick_rom.h — generated by tools/make_kick_header.py from YOUR ROM.\n")
        f.write("// DO NOT COMMIT OR REDISTRIBUTE: the Kickstart ROM is copyrighted.\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write(f"#define KICK_ROM_SIZE {len(rom)}u\n")
        f.write(f"#define KICK_ROM_CRC 0x{crc:08x}u\n")
        f.write("static const uint8_t kickstart_rom[] = {\n")
        for i in range(0, len(rom), 24):
            f.write("  " + ",".join(str(b) for b in rom[i:i+24]) + ",\n")
        f.write("};\n")
    print(f"Written: {out} ({os.path.getsize(out)//1024} KB of C source)")

if __name__ == "__main__":
    main()
