#!/usr/bin/env python3
"""
make_adf_header.py — generate esp32/wb_adf.h from YOUR .adf disk image.

The ADF (Workbench, a game you own, etc.) is embedded zlib-compressed in
the firmware and decompressed to PSRAM at boot. You must legally own the
software on the disk image. Workbench disks are licensed via Amiga Forever.

Usage:
    python3 make_adf_header.py mydisk.adf [output_dir]

The generated wb_adf.h is git-ignored on purpose: NEVER commit it.
"""
import sys, os, zlib

ADF_SIZE = 901120                # standard 880KB DD Amiga floppy

def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    path = sys.argv[1]
    outdir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "esp32")

    adf = open(path, "rb").read()
    if len(adf) != ADF_SIZE:
        print(f"WARNING: {len(adf)} bytes, expected {ADF_SIZE} (standard DD ADF).")
    comp = zlib.compress(adf, 9)
    crc = zlib.crc32(adf) & 0xFFFFFFFF
    boot = "bootable (DOS)" if adf[:3] == b"DOS" else "custom/non-DOS bootblock"
    print(f"ADF: {len(adf)} -> {len(comp)} bytes compressed "
          f"({100*len(comp)//len(adf)}%), CRC {crc:08X}, {boot}")

    out = os.path.join(outdir, "wb_adf.h")
    with open(out, "w") as f:
        f.write("// wb_adf.h — generated by tools/make_adf_header.py from YOUR disk image.\n")
        f.write("// DO NOT COMMIT OR REDISTRIBUTE copyrighted disk contents.\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write(f"#define WB_ADF_SIZE {len(adf)}u\n")
        f.write(f"#define WB_ADF_CRC  0x{crc:08x}u\n")
        f.write(f"#define WB_ADF_COMP_SIZE {len(comp)}u\n")
        f.write("static const uint8_t wb_adf_comp[] = {\n")
        for i in range(0, len(comp), 24):
            f.write("  " + ",".join(str(b) for b in comp[i:i+24]) + ",\n")
        f.write("};\n")
    print(f"Written: {out} ({os.path.getsize(out)//1024} KB of C source)")
    print("Tip: if the sketch no longer fits, select Tools -> Partition Scheme ->")
    print("     'Huge APP (3MB No OTA/1MB SPIFFS)' in the Arduino IDE.")

if __name__ == "__main__":
    main()
